### ISSUE TITLE
'Follow' / 'Unfollow' buttons appear in user's own profile

### ISSUE THREAD

**Issue by duckCooker** [andyalbert/frontend#2]
Issue:
User can see 'follow' and 'unfollow' buttons in his/her own profile. That's conflicting with the UI convenience and DB design  which prohibit user from following him/herself.

Suggestion:
Check the id of the main user against the id of the user being viewed and suppress the appearance of those 2 buttons

**Comment by duckCooker** [comment]
Check the id of the main user against the id the user being viewed and suppress the appearance of  those 2 buttons

**Comment by andyalbert** [comment]
Done, Follow/Unfollow removed, they're not gonna be checked as we didn't add viewing other users' profile to the application
